const { nanoid } = require('nanoid');
const fs = require('fs-extra');
const path = require('path');
const { spawn } = require('child_process');
const multer = require('fastify-multer');
const progressService = require('../services/progressService');
const { loadJobsFromDisk, startJobHealthCheck } = require('../utils/jobRecovery');
const jobHistory = require('../utils/jobHistory');

// In-memory job storage (use Redis in production)
let jobs = new Map();
let jobHealthCheckInterval = null;

// Load jobs from disk on module load
const usersDir = process.env.USERS_DIR || path.join(__dirname, '../../../users');
const defaultUserSessionsDir = path.join(usersDir, 'default/sessions');
loadJobsFromDisk(defaultUserSessionsDir).then(loadedJobs => {
  // DON'T reassign jobs! Copy entries to keep same reference
  jobs.clear();
  for (const [key, value] of loadedJobs.entries()) {
    jobs.set(key, value);
  }
  // Start health check for stuck jobs
  jobHealthCheckInterval = startJobHealthCheck(jobs, usersDir);
  console.log(`✅ Job recovery system initialized with ${jobs.size} jobs`);
}).catch(err => {
  console.error('❌ Failed to load jobs from disk:', err);
});

// Helper function to get user session directory
function getUserSessionDir(userId = 'default', sessionId) {
  const userDir = path.join(usersDir, userId, 'sessions', sessionId);
  return userDir;
}

// Helper function to get user uploads directory
function getUserUploadsDir(userId = 'default', sessionId) {
  return path.join(getUserSessionDir(userId, sessionId), 'uploads');
}

// Helper function to get user exports directory
function getUserExportsDir(userId = 'default', sessionId) {
  return path.join(getUserSessionDir(userId, sessionId), 'exports');
}

// Configure multer for direct upload to session directory
// We'll dynamically set the destination for each upload
const storage = multer.diskStorage({
  destination: (req, file, cb) => {
    // Session ID will be attached by preHandler or extracted from body
    if (!req.sessionId) {
      return cb(new Error('Session ID not initialized'));
    }
    
    const userId = req.userId || 'default';
    const sessionPath = getUserUploadsDir(userId, req.sessionId);
    
    // Create directory synchronously (multer destination doesn't handle async well)
    const fsSync = require('fs');
    try {
      fsSync.mkdirSync(sessionPath, { recursive: true });
      cb(null, sessionPath);
    } catch (err) {
      cb(err);
    }
  },
  filename: (req, file, cb) => {
    // Keep original filename
    cb(null, file.originalname);
  }
});

// Pre-handler to extract sessionId and userId before multer processes files
async function extractSessionId(request, reply) {
  // Extract userId from header (generated by frontend from IndexedDB)
  const userId = request.headers['x-user-id'];
  if (!userId) {
    return reply.status(400).send({
      success: false,
      message: 'Missing x-user-id header'
    });
  }
  request.userId = userId;
  
  // Check for session ID in header (simplest approach - no need to parse multipart)
  const sessionIdFromHeader = request.headers['x-session-id'];
  
  if (sessionIdFromHeader && /^sess_\d+_[A-Za-z0-9_-]{8}$/.test(sessionIdFromHeader)) {
    request.sessionId = sessionIdFromHeader;
    request.isChunkedContinuation = true;
    console.log('📦 Chunked upload continuation:', sessionIdFromHeader, `(User: ${userId})`);
  } else {
    // No sessionId found, create new
    request.sessionId = `sess_${Date.now()}_${nanoid(8)}`;
    request.isChunkedContinuation = false;
    console.log('📤 New upload session:', request.sessionId, `(User: ${userId})`);
  }
}

const upload = multer({
  storage: storage,
  limits: {
    fileSize: parseInt(process.env.MAX_FILE_SIZE_MB || 10) * 1024 * 1024,
    files: parseInt(process.env.MAX_IMAGES_PER_SESSION || 300)
  },
  fileFilter: (req, file, cb) => {
    const ext = path.extname(file.originalname).toLowerCase().replace('.', '');
    const allowedFormats = (process.env.ALLOWED_FORMATS || 'jpg,jpeg,png,heic,heif').split(',');
    
    if (!allowedFormats.includes(ext)) {
      cb(new Error(`File ${file.originalname} has unsupported format. Allowed: ${allowedFormats.join(', ')}`));
      return;
    }
    cb(null, true);
  }
});

async function uploadRoutes(fastify, options) {
  
  // POST /api/upload - Upload images for processing (using fastify-multer)
  fastify.post('/upload', { 
    preHandler: [
      extractSessionId,
      upload.array('files', parseInt(process.env.MAX_IMAGES_PER_SESSION || 300))
    ]
  }, async (request, reply) => {
    try {
      const userId = request.userId || 'default';
      
      // SessionId already set by extractSessionId preHandler
      const sessionId = request.sessionId;
      const isChunkedContinuation = request.isChunkedContinuation;
      
      // Debug logging
      console.log('Upload request received:', {
        userId,
        filesCount: request.files?.length || 0,
        bodyKeys: Object.keys(request.body || {}),
        contentType: request.headers['content-type'],
        isChunked: isChunkedContinuation
      });
      
      const uploadedFiles = request.files || [];
      const { quality = 'high', formats: formatsStr = 'usdz,obj,stl' } = request.body || {};
      const formats = formatsStr.split(',').map(f => f.trim());
      
      const sessionPath = getUserUploadsDir(userId, sessionId);
      const sessionMetaPath = path.join(getUserSessionDir(userId, sessionId), 'session.json');
      
      // Files are already uploaded to sessionPath by multer - no need to copy!
      // Just calculate total size and format file list
      let totalSize = 0;
      const formattedFiles = [];
      
      console.log(`Files uploaded directly to ${sessionPath}`);
      
      // If chunked continuation, load existing metadata
      let existingMetadata = null;
      if (isChunkedContinuation && await fs.pathExists(sessionMetaPath)) {
        try {
          existingMetadata = await fs.readJSON(sessionMetaPath);
          console.log(`📦 Loaded existing metadata: ${existingMetadata.imageCount} files already uploaded`);
        } catch (e) {
          console.error('Failed to load existing metadata:', e);
        }
      }
      
      for (let i = 0; i < uploadedFiles.length; i++) {
        const file = uploadedFiles[i];
        
        formattedFiles.push({
          filename: file.originalname,
          size: file.size
        });
        totalSize += file.size;
      }
      
      // Add existing size if chunked
      const existingSize = existingMetadata?.totalSize || 0;
      const existingCount = existingMetadata?.imageCount || 0;
      const newTotalSize = existingSize + totalSize;
      const newTotalCount = existingCount + uploadedFiles.length;
      
      console.log(`Batch: ${uploadedFiles.length} files, ${(totalSize / 1024 / 1024).toFixed(2)}MB`);
      console.log(`Total: ${newTotalCount} files, ${(newTotalSize / 1024 / 1024).toFixed(2)}MB`);
      
      // For chunked upload, only validate on completion (indicated by body param)
      const isCompleteUpload = !request.body?.moreChunks || request.body?.moreChunks === 'false';
      
      // Validate minimum images (only for complete uploads)
      if (isCompleteUpload && newTotalCount < 30) {
        await fs.rm(sessionPath, { recursive: true, force: true });
        return reply.status(400).send({
          success: false,
          error: 'Insufficient images',
          message: `Uploaded ${newTotalCount} images. Minimum 30 images required for processing.`
        });
      }
      
      // Check total size limit
      const maxTotalSize = parseInt(process.env.MAX_TOTAL_SIZE_GB || 3) * 1024 * 1024 * 1024;
      if (newTotalSize > maxTotalSize) {
        await fs.rm(sessionPath, { recursive: true, force: true });
        return reply.status(413).send({
          success: false,
          error: 'Total upload too large',
          message: `Total size exceeds ${process.env.MAX_TOTAL_SIZE_GB || 3}GB limit`
        });
      }
      
      // If this is not the final chunk, return sessionId and wait for more
      if (!isCompleteUpload) {
        // Update metadata for partial upload
        const partialMeta = {
          sessionId,
          status: 'uploading',
          imageCount: newTotalCount,
          totalSize: newTotalSize,
          quality,
          formats,
          createdAt: existingMetadata?.createdAt || new Date().toISOString(),
          updatedAt: new Date().toISOString()
        };
        
        await fs.ensureDir(path.dirname(sessionMetaPath));
        await fs.writeJSON(sessionMetaPath, partialMeta, { spaces: 2 });
        
        return reply.status(202).send({
          success: true,
          message: 'Batch uploaded, waiting for more',
          data: {
            sessionId,
            uploadedCount: newTotalCount,
            totalSize: `${(newTotalSize / 1024 / 1024).toFixed(2)} MB`,
            statusUrl: `/api/jobs/${sessionId}`
          }
        });
      }
      
      // This is the final chunk - proceed with processing
      // Create session metadata
      const sessionMeta = {
        sessionId,
        status: 'pending',
        progress: 0,
        imageCount: newTotalCount,
        totalSize: newTotalSize,
        quality,
        formats,
        createdAt: new Date().toISOString(),
        uploadPath: sessionPath,
        files: formattedFiles
      };
      
      await fs.writeFile(sessionMetaPath, JSON.stringify(sessionMeta, null, 2));
      jobs.set(sessionId, sessionMeta);
      
      // Start processing asynchronously
      processJob(sessionId, sessionPath, quality, formats, userId).catch(err => {
        fastify.log.error(`Job ${sessionId} failed:`, err);
      });
      
      return reply.status(202).send({
        success: true,
        message: 'Upload successful, processing started',
        data: {
          sessionId,
          uploadedCount: newTotalCount,
          totalSize: `${(newTotalSize / 1024 / 1024).toFixed(2)} MB`,
          quality,
          formats,
          estimatedTime: await jobHistory.getEstimatedTime(newTotalCount, quality),
          statusUrl: `/api/jobs/${sessionId}`
        }
      });
      
    } catch (error) {
      fastify.log.error('Upload error:', error.message);
      fastify.log.error('Upload error stack:', error.stack);
      console.error('❌ Upload error details:', error);
      return reply.status(500).send({
        success: false,
        error: 'Upload failed',
        message: error.message || 'Unknown error'
      });
    }
  });
}

// Helper: Complete job and prepare results
async function completeJob(sessionId, job, outputPath, sessionFile, formats) {
  if (!job || job.status === 'completed') {
    // Already completed
    console.log(`[${sessionId}] Job already marked as completed, skipping`);
    return;
  }
  
  // Mark as completing to prevent duplicate calls
  if (job._completing) {
    console.log(`[${sessionId}] Job completion already in progress, skipping duplicate`);
    return;
  }
  job._completing = true;
  
  try {
    console.log(`[${sessionId}] Completing job...`);
    
    // Convert USDZ to OBJ/STL if needed
    const usdzPath = path.join(outputPath, 'model.usdz');
    console.log(`[${sessionId}] 🔍 Checking for USDZ at: ${usdzPath}`);
    const usdzExists = await fs.stat(usdzPath).then(() => true).catch(() => false);
    console.log(`[${sessionId}] 🔍 USDZ exists: ${usdzExists}`);
    
    if (usdzExists) {
      console.log(`[${sessionId}] 🔍 Requested formats: ${JSON.stringify(formats)}`);
      const needsConversion = formats.some(f => ['obj', 'stl'].includes(f));
      console.log(`[${sessionId}] 🔍 Needs conversion: ${needsConversion}`);
      
      if (needsConversion) {
        console.log(`[${sessionId}] ⚙️ Starting conversion process...`);
        
        // Broadcast Extracting stage
        job.currentStage = 'Extracting';
        jobs.set(sessionId, job);
        progressService.updateStage(sessionId, 'Extracting');
        await fs.writeFile(sessionFile, JSON.stringify(job, null, 2)).catch(() => {});
        console.log(`[${sessionId}] ✅ Broadcast Extracting stage`);
        
        try {
          console.log(`[${sessionId}] 📦 Loading converter module...`);
          const { convertUSDZToFormats } = require('../utils/convertFormats.js');
          console.log(`[${sessionId}] ✅ Converter module loaded, calling function...`);
          
          // Add timeout for conversion (5 minutes max)
          const conversionPromise = convertUSDZToFormats(usdzPath, outputPath);
          const timeoutPromise = new Promise((_, reject) => 
            setTimeout(() => reject(new Error('Conversion timeout')), 300000)
          );
          
          const result = await Promise.race([conversionPromise, timeoutPromise]);
          console.log(`[${sessionId}] ✅ Format conversion completed, result: ${result}`);
          
          // Verify files were created
          const objPath = path.join(outputPath, 'model.obj');
          const stlPath = path.join(outputPath, 'model.stl');
          const objExists = await fs.stat(objPath).then(() => true).catch(() => false);
          const stlExists = await fs.stat(stlPath).then(() => true).catch(() => false);
          
          console.log(`[${sessionId}] Files created - OBJ: ${objExists}, STL: ${stlExists}`);
        } catch (convErr) {
          console.error(`[${sessionId}] ⚠️  Format conversion failed: ${convErr.message}`);
          // Continue anyway - at least we have USDZ
        }
      }
    }
    
    job.status = 'completed';
    job.progress = 100;
    job.currentStage = 'Complete'; // Set final stage
    job.completedAt = new Date().toISOString();
    delete job._completing; // Clean up completion flag
    
    // Update job in memory and broadcast Complete stage
    jobs.set(sessionId, job);
    progressService.updateStage(sessionId, 'Complete');
    console.log(`[${sessionId}] ✅ Broadcast Complete stage`);
    
    // Get result files
    try {
      const files = await fs.readdir(outputPath);
      job.results = {};
      
      for (const file of files) {
        if (file.startsWith('.') || file === 'checkpoints') continue; // Skip hidden and checkpoint dirs
        
        const filePath = path.join(outputPath, file);
        const stats = await fs.stat(filePath);
        
        if (stats.isFile()) {
          const ext = path.extname(file).replace('.', '');
          
          job.results[ext] = {
            filename: file,
            url: `/api/download/${sessionId}/${file}`,
            size: `${(stats.size / 1024 / 1024).toFixed(2)} MB`
          };
        }
      }
    } catch (err) {
      console.error(`[${sessionId}] Failed to read result files: ${err.message}`);
    }
    
    jobs.set(sessionId, job);
    
    // Broadcast completion via WebSocket
    progressService.complete(sessionId, job.results);
    
    // Log job to history for better time estimation
    await jobHistory.logJob(job).catch(err => {
      console.error(`[${sessionId}] Failed to log job history:`, err);
    });
    
    // Save to session file
    await fs.writeFile(sessionFile, JSON.stringify(job, null, 2));
    
    console.log(`[${sessionId}] ✅ Job completed with results:`, Object.keys(job.results || {}));
    
  } catch (error) {
    console.error(`[${sessionId}] Error completing job:`, error);
  }
}

// Helper: Process job with Swift CLI
async function processJob(sessionId, inputPath, quality, formats, userId = 'default') {
  console.log(`[${sessionId}] 🚀 processJob CALLED with input=${inputPath}, user=${userId}`);
  
  const outputPath = getUserExportsDir(userId, sessionId);
  
  // Use wrapper script (handles sudo automatically)
  const wrapperPath = process.env.WRAPPER_PATH || path.join(__dirname, '../../../core-engine/run-heyphom.sh');
  
  const sessionFile = path.join(getUserSessionDir(userId, sessionId), 'session.json');
  
  await fs.mkdir(outputPath, { recursive: true });
  
  // Update job status to processing
  const job = jobs.get(sessionId);
  console.log(`[${sessionId}] 🔍 Job from Map at processJob start: ${job ? 'EXISTS' : 'NULL'}, status: ${job?.status}`);
  
  if (job) {
    job.status = 'processing';
    job.startedAt = new Date().toISOString();
    job.engine = 'realitykit';
    jobs.set(sessionId, job);
    
    // Save to session file
    await fs.writeFile(sessionFile, JSON.stringify(job, null, 2));
  }
  
  return new Promise((resolve, reject) => {
    const args = [
      '--input', inputPath,
      '--output', outputPath,
      '--quality', quality,
      '--formats', formats.join(',')
    ];
    
    // Run wrapper script (which calls sudo internally)
    const child = spawn(wrapperPath, args);
    
    let stdout = '';
    let stderr = '';
    
    child.stdout.on('data', async (data) => {
      stdout += data.toString();
      const lines = data.toString().split('\n');
      
      for (const line of lines) {
        if (!line.trim()) continue;
        
        console.log(`[${sessionId}] ${line.trim()}`);
        
        // Parse progress: "📊 PROGRESS: 45"
        const progressMatch = line.match(/📊 PROGRESS:\s*(\d+)/);
        if (progressMatch && job) {
          const progress = parseInt(progressMatch[1]);
          job.progress = progress;
          jobs.set(sessionId, job);
          
          // Broadcast via WebSocket
          progressService.updateProgress(sessionId, progress);
          
          // Save progress to session file
          try {
            await fs.writeFile(sessionFile, JSON.stringify(job, null, 2));
          } catch (err) {
            console.error(`Failed to save progress: ${err.message}`);
          }
        }
        
        // Parse stage: "📝 STAGE: Feature Detection"
        const stageMatch = line.match(/📝 STAGE:\s*(.+)/);
        if (stageMatch && job) {
          const stage = stageMatch[1].trim();
          
          // If stage is "Completed", trigger completion immediately (don't broadcast yet)
          if (stage === 'Completed') {
            console.log(`[${sessionId}] 🎉 Processing completed, preparing results...`);
            
            // Don't broadcast "Completed" stage - let completeJob() handle everything
            // Call completeJob immediately (async, but don't wait)
            completeJob(sessionId, job, outputPath, sessionFile, formats).catch(err => {
              console.error(`[${sessionId}] Error in completeJob:`, err);
            });
          } else {
            // For other stages, broadcast normally
            job.currentStage = stage;
            jobs.set(sessionId, job);
            
            // Broadcast via WebSocket
            progressService.updateStage(sessionId, stage);
            
            // Save stage to session file
            try {
              await fs.writeFile(sessionFile, JSON.stringify(job, null, 2));
            } catch (err) {
              console.error(`Failed to save stage: ${err.message}`);
            }
          }
        }
      }
    });
    
    child.stderr.on('data', (data) => {
      stderr += data.toString();
      console.error(`[${sessionId}] ${data.toString().trim()}`);
    });
    
    child.on('close', async (code) => {
      console.log(`[${sessionId}] Process exited with code ${code}`);
      
      if (code === 0) {
        // Processing successful
        // Re-fetch job from Map (don't use closure variable)
        const currentJob = jobs.get(sessionId);
        console.log(`[${sessionId}] 🔍 Current job status: ${currentJob?.status}, _completing: ${currentJob?._completing}`);
        
        // Call completeJob if not already completed
        if (currentJob && currentJob.status !== 'completed') {
          console.log(`[${sessionId}] 🚀 Calling completeJob...`);
          await completeJob(sessionId, currentJob, outputPath, sessionFile, formats);
        } else {
          console.log(`[${sessionId}] ⚠️  Job already completed (status: ${currentJob?.status}), skipping duplicate completion`);
        }
        
        resolve();
      } else {
        // Processing failed
        if (job) {
          job.status = 'failed';
          job.error = stderr || stdout || 'Processing failed';
          job.failedAt = new Date().toISOString();
          jobs.set(sessionId, job);
          
          // Broadcast failure via WebSocket
          progressService.fail(sessionId, job.error);
          
          // Save to session file
          await fs.writeFile(sessionFile, JSON.stringify(job, null, 2));
        }
        
        reject(new Error(`Processing failed with code ${code}: ${stderr || stdout}`));
      }
    });
  });
}

// Helper: Load job into memory Map (for manual processing after restart)
function loadJobIntoMemory(sessionId, jobData) {
  jobs.set(sessionId, jobData);
}

// Helper: Estimate processing time
function getEstimatedTime(imageCount, quality) {
  const baseTime = {
    low: 0.1,
    medium: 0.15,
    high: 0.2,
    ultra: 0.3
  }[quality] || 0.2;
  
  const minutes = Math.ceil(imageCount * baseTime);
  
  if (minutes < 60) {
    return `${minutes} minutes`;
  } else {
    const hours = Math.floor(minutes / 60);
    const mins = minutes % 60;
    return `${hours}h ${mins}m`;
  }
}

// Export for external use (e.g., github-dataset routes)
module.exports = uploadRoutes;
module.exports.processJob = processJob;
module.exports.loadJobIntoMemory = loadJobIntoMemory;
module.exports.progressService = progressService;
module.exports.jobs = jobs; // Export jobs Map for shared access
module.exports.getEstimatedTime = getEstimatedTime; // Export for GitHub dataset
module.exports.getUserSessionDir = getUserSessionDir; // Export directory helpers
module.exports.getUserUploadsDir = getUserUploadsDir;
module.exports.getUserExportsDir = getUserExportsDir;
